<h3>Change Password for <?php echo $this->zfcUserDisplayName() ?></h3>
<?php if ($status === true) : ?>
<div class="alert alert-success">Password changed successfully.</div>
<?php elseif ($status === false) : ?>
<div class="alert alert-error">Unable to update your password. Please try again.</div>
<?php endif; ?>
<?php

$form = $this->changePasswordForm;

$form->prepare();
$form->setAttribute('action', $this->url('zfcuser/changepassword'));
$form->setAttribute('method', 'post');
$form->setAttribute('class', 'form-horizontal');

$emailElement = $form->get('identity');
$emailElement->setValue($this->zfcUserIdentity()->getEmail());

echo $this->form()->openTag($form);

?>
<div class="control-group">
<?php echo $this->formElementErrors($form->get('identity')); ?>
<div><?php echo $this->formInput($form->get('identity')); ?></div>

<div><?php echo $this->formLabel($form->get('credential')); ?></div>
<div><?php
echo $this->formInput($form->get('credential')) . $this->formElementErrors($form->get('credential'));
?></div>

<div><?php echo $this->formLabel($form->get('newCredential')); ?></div>
<div><?php
echo $this->formInput($form->get('newCredential')) . $this->formElementErrors($form->get('newCredential'));
?></div>

<div><?php echo $this->formLabel($form->get('newCredentialVerify')); ?></div>
<div><?php
echo $this->formInput($form->get('newCredentialVerify')) . $this->formElementErrors($form->get('newCredentialVerify'));
?></div>

<div class="control-group">
<?php $form->get('submit')->setAttribute('class','btn'); ?>
<?php echo $this->formInput($form->get('submit')); ?>
</div>

</div>

<?php echo $this->form()->closeTag(); ?>
