<?php
foreach ($houses as $house) {
	echo '<div class="well">';
	echo '<a href="' . $this->url('details', array('username' => $house->getCreatedUser()->getUsername(), 'propertyType' => 'house', 'propertyId' => $house->getId())) . '">';
	echo $house->getAddress()->getHouse() . ' ' . $house->getAddress()->getVillage() . '<br />';
	echo '</a>';
	echo $house->getCost() . '<br />';
	echo $house->getType()->getTitle() . '<br />';
	echo '<br />';

	if (0 < count($rooms[$house->getId()])) {
		echo count($rooms[$house->getId()]) . ' rooms available';
		foreach ($rooms[$house->getId()] as $room) {
			echo '<br />' . $room->getCost() . ' (' . $room->getSize()->getWidth() . 'x' . $room->getSize()->getHeight() . 'x' . $room->getSize()->getLength() . ') ';
		}
	}
	?>

	<div class="btn-group">
		<button class="btn" id="ratePositive"><?php echo $house->getPositiveRateNumber() ?></button>
		<button class="btn" id="rateNegative"><?php echo $house->getNegativeRateNumber() ?></button>
	</div>

	<div id="message"></div>

	<form method="post" onsubmit="return false;">
		<input type="hidden" name="houseId" class="houseId" value="<?php echo $house->getId() ?>" />
		<input type="hidden" name="rate" class="rateValue" value="1" />
		<input type="submit" class="btn rateButton" value="UP" />
	</form>

	<form method="post" onsubmit="return false;">
		<input type="hidden" name="houseId" class="houseId" value="<?php echo $house->getId() ?>" />
		<input type="hidden" name="rate" class="rateValue" value="0" />
		<input type="submit" class="btn rateButton" value="DOWN" />
	</form>

	<?php
	echo '</div>';
}
?>

<?php echo $this->paginationControl($houses, 'Sliding', 'real-estate/houses-list/pagination-house-list.phtml'); ?>

<script type="text/javascript">
	jQuery(document).ready(function(){
		jQuery('.rateButton').click(function(){
			var houseId = jQuery(this).parent().find(".houseId").val();
			var rateValue = jQuery(this).parent().find(".rateValue").val();
			
			jQuery.ajax({
				'url' : "<?php echo $this->url('rate') ?>",
				'type' : "POST",
				'data' : {"houseId" : houseId, "rateValue" : rateValue},
				'beforeSend' : function(){
					
				},
				'error' : function(){
					jQuery('#message').html('<div class="alert alert-error">ERROR</div>');
				},
				'success': function(data){
					var result =  jQuery.parseJSON(data);
					console.log(result);
					if(result.already){
						jQuery('#message').html('<div class="alert alert-block">ALEADY</div>');
					}
					if(!result.loggedin){
						jQuery('#message').html('<div class="alert alert-block">YOU MUST LOGGIN TO VOTE, <a href="<?php echo $this->url('zfcuser/login') ?>">Login</a></div>');
					}
					jQuery('#ratePositive').html(result.positive);
					jQuery('#rateNegative').html(result.negative);
					
				}
			});
			console.log(houseId);
			console.log(rateValue);
		});
	});
</script>