<?php
foreach ($houses as $house) {
	echo '<pre>';
	echo '<a href="' . $this->url('details', array('username' => $house->getCreatedUser()->getUsername(), 'propertyType' => 'house', 'propertyId' => $house->getId())) . '">';
	echo $house->getAddress()->getHouse() . ' ' . $house->getAddress()->getVillage() . '<br />';
	echo '</a>';
	echo $house->getCost() . '<br />';
	echo $house->getType()->getTitle() . '<br />';
	echo '<br />';

	if (0 < count($rooms[$house->getId()])) {
		echo count($rooms[$house->getId()]) . ' rooms available';
		foreach ($rooms[$house->getId()] as $room) {
			echo '<br />' . $room->getCost() . ' (' . $room->getSize()->getWidth() . 'x' . $room->getSize()->getHeight() . 'x' . $room->getSize()->getLength() . ') ';
		}
	}


//	echo '<button class="btn rateButton">+</button>';
//	echo '<button class="btn rateButton">-</button>';

	echo '</pre>';
}
?>

<?php echo $this->paginationControl($houses, 'Sliding', 'real-estate/houses-list/pagination-house-list.phtml'); ?>

<script type="text/javascript">
	jQuery(document).ready(function(){
		jQuery('.rateButton').click(function(){
			jQuery.ajax({
				url: "<?php echo $this->url('rate') ?>",
				type: "post",
				data: jQuery(this).val(),
				success: function(){
					console.log("SUCCESS");
				}
			});
		});
	});
</script>