<?php
$form->prepare();
$form->setAttribute('action', $this->url('room/action', array('action' => 'new', 'houseId' => $houseId)));
$form->setAttribute('method', 'post');
?>
<?php echo $this->form()->openTag($form) ?>
<dl>
	<?php foreach ($form as $element): ?>
		<dd><?php echo $this->formRow($element) ?></dd>
	<?php endforeach ?>
</dl>
<?php echo $this->form()->closeTag() ?>

<script type="text/javascript">
	jQuery(document).ready(function(){
		jQuery('#addRoom').click(function(){
			
		});
	});
</script>