<?php

namespace DoctrineORMModule\Proxy\__CG__\RealEstate\Entity;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class Permission extends \RealEstate\Entity\Permission implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["id"];
        }
        $this->__load();
        return parent::getId();
    }

    public function setPid($pid)
    {
        $this->__load();
        return parent::setPid($pid);
    }

    public function getPid()
    {
        $this->__load();
        return parent::getPid();
    }

    public function setHidden($hidden)
    {
        $this->__load();
        return parent::setHidden($hidden);
    }

    public function getHidden()
    {
        $this->__load();
        return parent::getHidden();
    }

    public function setDisabled($disabled)
    {
        $this->__load();
        return parent::setDisabled($disabled);
    }

    public function getDisabled()
    {
        $this->__load();
        return parent::getDisabled();
    }

    public function setDeleted($deleted)
    {
        $this->__load();
        return parent::setDeleted($deleted);
    }

    public function getDeleted()
    {
        $this->__load();
        return parent::getDeleted();
    }

    public function setCreatedTime($createdTime)
    {
        $this->__load();
        return parent::setCreatedTime($createdTime);
    }

    public function getCreatedTime()
    {
        $this->__load();
        return parent::getCreatedTime();
    }

    public function setLastModifiedTime($lastModifiedTime)
    {
        $this->__load();
        return parent::setLastModifiedTime($lastModifiedTime);
    }

    public function getLastModifiedTime()
    {
        $this->__load();
        return parent::getLastModifiedTime();
    }

    public function setValidTimeStart($validTimeStart)
    {
        $this->__load();
        return parent::setValidTimeStart($validTimeStart);
    }

    public function getValidTimeStart()
    {
        $this->__load();
        return parent::getValidTimeStart();
    }

    public function setValidTimeEnd($validTimeEnd)
    {
        $this->__load();
        return parent::setValidTimeEnd($validTimeEnd);
    }

    public function getValidTimeEnd()
    {
        $this->__load();
        return parent::getValidTimeEnd();
    }

    public function setTitle($title)
    {
        $this->__load();
        return parent::setTitle($title);
    }

    public function getTitle()
    {
        $this->__load();
        return parent::getTitle();
    }

    public function addRole(\RealEstate\Entity\UserRole $role)
    {
        $this->__load();
        return parent::addRole($role);
    }

    public function removeRole(\RealEstate\Entity\UserRole $role)
    {
        $this->__load();
        return parent::removeRole($role);
    }

    public function getRole()
    {
        $this->__load();
        return parent::getRole();
    }

    public function setCreatedUser(\RealEstate\Entity\User $createdUser = NULL)
    {
        $this->__load();
        return parent::setCreatedUser($createdUser);
    }

    public function getCreatedUser()
    {
        $this->__load();
        return parent::getCreatedUser();
    }

    public function setLastModifiedUser(\RealEstate\Entity\User $lastModifiedUser = NULL)
    {
        $this->__load();
        return parent::setLastModifiedUser($lastModifiedUser);
    }

    public function getLastModifiedUser()
    {
        $this->__load();
        return parent::getLastModifiedUser();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'pid', 'hidden', 'disabled', 'deleted', 'createdTime', 'lastModifiedTime', 'validTimeStart', 'validTimeEnd', 'title', 'role', 'createdUser', 'lastModifiedUser');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}