<?php

namespace DoctrineORMModule\Proxy\__CG__\RealEstate\Entity;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class PersonalDetails extends \RealEstate\Entity\PersonalDetails implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function getUid()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["uid"];
        }
        $this->__load();
        return parent::getUid();
    }

    public function setPid($pid)
    {
        $this->__load();
        return parent::setPid($pid);
    }

    public function getPid()
    {
        $this->__load();
        return parent::getPid();
    }

    public function setHidden($hidden)
    {
        $this->__load();
        return parent::setHidden($hidden);
    }

    public function getHidden()
    {
        $this->__load();
        return parent::getHidden();
    }

    public function setDisabled($disabled)
    {
        $this->__load();
        return parent::setDisabled($disabled);
    }

    public function getDisabled()
    {
        $this->__load();
        return parent::getDisabled();
    }

    public function setDeleted($deleted)
    {
        $this->__load();
        return parent::setDeleted($deleted);
    }

    public function getDeleted()
    {
        $this->__load();
        return parent::getDeleted();
    }

    public function setCreatedtime($createdtime)
    {
        $this->__load();
        return parent::setCreatedtime($createdtime);
    }

    public function getCreatedtime()
    {
        $this->__load();
        return parent::getCreatedtime();
    }

    public function setCreateduseruid($createduseruid)
    {
        $this->__load();
        return parent::setCreateduseruid($createduseruid);
    }

    public function getCreateduseruid()
    {
        $this->__load();
        return parent::getCreateduseruid();
    }

    public function setLastmodifiedtime($lastmodifiedtime)
    {
        $this->__load();
        return parent::setLastmodifiedtime($lastmodifiedtime);
    }

    public function getLastmodifiedtime()
    {
        $this->__load();
        return parent::getLastmodifiedtime();
    }

    public function setLastmodifieduseruid($lastmodifieduseruid)
    {
        $this->__load();
        return parent::setLastmodifieduseruid($lastmodifieduseruid);
    }

    public function getLastmodifieduseruid()
    {
        $this->__load();
        return parent::getLastmodifieduseruid();
    }

    public function setValidtimestart($validtimestart)
    {
        $this->__load();
        return parent::setValidtimestart($validtimestart);
    }

    public function getValidtimestart()
    {
        $this->__load();
        return parent::getValidtimestart();
    }

    public function setValidtimeend($validtimeend)
    {
        $this->__load();
        return parent::setValidtimeend($validtimeend);
    }

    public function getValidtimeend()
    {
        $this->__load();
        return parent::getValidtimeend();
    }

    public function setFirstname($firstname)
    {
        $this->__load();
        return parent::setFirstname($firstname);
    }

    public function getFirstname()
    {
        $this->__load();
        return parent::getFirstname();
    }

    public function setLastname($lastname)
    {
        $this->__load();
        return parent::setLastname($lastname);
    }

    public function getLastname()
    {
        $this->__load();
        return parent::getLastname();
    }

    public function setGender($gender)
    {
        $this->__load();
        return parent::setGender($gender);
    }

    public function getGender()
    {
        $this->__load();
        return parent::getGender();
    }

    public function setJob($job)
    {
        $this->__load();
        return parent::setJob($job);
    }

    public function getJob()
    {
        $this->__load();
        return parent::getJob();
    }

    public function setAge($age)
    {
        $this->__load();
        return parent::setAge($age);
    }

    public function getAge()
    {
        $this->__load();
        return parent::getAge();
    }

    public function setEmail($email)
    {
        $this->__load();
        return parent::setEmail($email);
    }

    public function getEmail()
    {
        $this->__load();
        return parent::getEmail();
    }

    public function setPhonenumber1($phonenumber1)
    {
        $this->__load();
        return parent::setPhonenumber1($phonenumber1);
    }

    public function getPhonenumber1()
    {
        $this->__load();
        return parent::getPhonenumber1();
    }

    public function setPhonenumber2($phonenumber2)
    {
        $this->__load();
        return parent::setPhonenumber2($phonenumber2);
    }

    public function getPhonenumber2()
    {
        $this->__load();
        return parent::getPhonenumber2();
    }

    public function setOthers($others)
    {
        $this->__load();
        return parent::setOthers($others);
    }

    public function getOthers()
    {
        $this->__load();
        return parent::getOthers();
    }

    public function setUseruid($useruid)
    {
        $this->__load();
        return parent::setUseruid($useruid);
    }

    public function getUseruid()
    {
        $this->__load();
        return parent::getUseruid();
    }

    public function setPersonaltypeuid($personaltypeuid)
    {
        $this->__load();
        return parent::setPersonaltypeuid($personaltypeuid);
    }

    public function getPersonaltypeuid()
    {
        $this->__load();
        return parent::getPersonaltypeuid();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'uid', 'pid', 'hidden', 'disabled', 'deleted', 'createdtime', 'createduseruid', 'lastmodifiedtime', 'lastmodifieduseruid', 'validtimestart', 'validtimeend', 'firstname', 'lastname', 'gender', 'job', 'age', 'email', 'phonenumber1', 'phonenumber2', 'others', 'useruid', 'personaltypeuid');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}