<?php

namespace DoctrineORMModule\Proxy\__CG__\RealEstate\Entity;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class House extends \RealEstate\Entity\House implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["id"];
        }
        $this->__load();
        return parent::getId();
    }

    public function setPid($pid)
    {
        $this->__load();
        return parent::setPid($pid);
    }

    public function getPid()
    {
        $this->__load();
        return parent::getPid();
    }

    public function setHidden($hidden)
    {
        $this->__load();
        return parent::setHidden($hidden);
    }

    public function getHidden()
    {
        $this->__load();
        return parent::getHidden();
    }

    public function setDisabled($disabled)
    {
        $this->__load();
        return parent::setDisabled($disabled);
    }

    public function getDisabled()
    {
        $this->__load();
        return parent::getDisabled();
    }

    public function setDeleted($deleted)
    {
        $this->__load();
        return parent::setDeleted($deleted);
    }

    public function getDeleted()
    {
        $this->__load();
        return parent::getDeleted();
    }

    public function setCreatedTime($createdTime)
    {
        $this->__load();
        return parent::setCreatedTime($createdTime);
    }

    public function getCreatedTime()
    {
        $this->__load();
        return parent::getCreatedTime();
    }

    public function setLastModifiedTime($lastModifiedTime)
    {
        $this->__load();
        return parent::setLastModifiedTime($lastModifiedTime);
    }

    public function getLastModifiedTime()
    {
        $this->__load();
        return parent::getLastModifiedTime();
    }

    public function setValidTimeStart($validTimeStart)
    {
        $this->__load();
        return parent::setValidTimeStart($validTimeStart);
    }

    public function getValidTimeStart()
    {
        $this->__load();
        return parent::getValidTimeStart();
    }

    public function setValidTimeEnd($validTimeEnd)
    {
        $this->__load();
        return parent::setValidTimeEnd($validTimeEnd);
    }

    public function getValidTimeEnd()
    {
        $this->__load();
        return parent::getValidTimeEnd();
    }

    public function setIsRoomRent($isRoomRent)
    {
        $this->__load();
        return parent::setIsRoomRent($isRoomRent);
    }

    public function getIsRoomRent()
    {
        $this->__load();
        return parent::getIsRoomRent();
    }

    public function setCost($cost)
    {
        $this->__load();
        return parent::setCost($cost);
    }

    public function getCost()
    {
        $this->__load();
        return parent::getCost();
    }

    public function setAvailable($available)
    {
        $this->__load();
        return parent::setAvailable($available);
    }

    public function getAvailable()
    {
        $this->__load();
        return parent::getAvailable();
    }

    public function setImagePathAsJsonStringList($imagePathAsJsonStringList)
    {
        $this->__load();
        return parent::setImagePathAsJsonStringList($imagePathAsJsonStringList);
    }

    public function getImagePathAsJsonStringList()
    {
        $this->__load();
        return parent::getImagePathAsJsonStringList();
    }

    public function setOtherInfo($otherInfo)
    {
        $this->__load();
        return parent::setOtherInfo($otherInfo);
    }

    public function getOtherInfo()
    {
        $this->__load();
        return parent::getOtherInfo();
    }

    public function setCreatedUser(\RealEstate\Entity\User $createdUser = NULL)
    {
        $this->__load();
        return parent::setCreatedUser($createdUser);
    }

    public function getCreatedUser()
    {
        $this->__load();
        return parent::getCreatedUser();
    }

    public function setLastModifiedUser(\RealEstate\Entity\User $lastModifiedUser = NULL)
    {
        $this->__load();
        return parent::setLastModifiedUser($lastModifiedUser);
    }

    public function getLastModifiedUser()
    {
        $this->__load();
        return parent::getLastModifiedUser();
    }

    public function setUser(\RealEstate\Entity\User $user = NULL)
    {
        $this->__load();
        return parent::setUser($user);
    }

    public function getUser()
    {
        $this->__load();
        return parent::getUser();
    }

    public function setType(\RealEstate\Entity\HouseType $type = NULL)
    {
        $this->__load();
        return parent::setType($type);
    }

    public function getType()
    {
        $this->__load();
        return parent::getType();
    }

    public function setSize(\RealEstate\Entity\Size $size = NULL)
    {
        $this->__load();
        return parent::setSize($size);
    }

    public function getSize()
    {
        $this->__load();
        return parent::getSize();
    }

    public function setAddress(\RealEstate\Entity\Address $address = NULL)
    {
        $this->__load();
        return parent::setAddress($address);
    }

    public function getAddress()
    {
        $this->__load();
        return parent::getAddress();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'pid', 'hidden', 'disabled', 'deleted', 'createdTime', 'lastModifiedTime', 'validTimeStart', 'validTimeEnd', 'isRoomRent', 'cost', 'available', 'imagePathAsJsonStringList', 'otherInfo', 'createdUser', 'lastModifiedUser', 'user', 'type', 'size', 'address');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}