<?php

namespace DoctrineORMModule\Proxy\__CG__\RealEstate\Entity;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class Address extends \RealEstate\Entity\Address implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["id"];
        }
        $this->__load();
        return parent::getId();
    }

    public function setPid($pid)
    {
        $this->__load();
        return parent::setPid($pid);
    }

    public function getPid()
    {
        $this->__load();
        return parent::getPid();
    }

    public function setHidden($hidden)
    {
        $this->__load();
        return parent::setHidden($hidden);
    }

    public function getHidden()
    {
        $this->__load();
        return parent::getHidden();
    }

    public function setDisabled($disabled)
    {
        $this->__load();
        return parent::setDisabled($disabled);
    }

    public function getDisabled()
    {
        $this->__load();
        return parent::getDisabled();
    }

    public function setDeleted($deleted)
    {
        $this->__load();
        return parent::setDeleted($deleted);
    }

    public function getDeleted()
    {
        $this->__load();
        return parent::getDeleted();
    }

    public function setCreatedTime($createdTime)
    {
        $this->__load();
        return parent::setCreatedTime($createdTime);
    }

    public function getCreatedTime()
    {
        $this->__load();
        return parent::getCreatedTime();
    }

    public function setLastModifiedTime($lastModifiedTime)
    {
        $this->__load();
        return parent::setLastModifiedTime($lastModifiedTime);
    }

    public function getLastModifiedTime()
    {
        $this->__load();
        return parent::getLastModifiedTime();
    }

    public function setValidTimeStart($validTimeStart)
    {
        $this->__load();
        return parent::setValidTimeStart($validTimeStart);
    }

    public function getValidTimeStart()
    {
        $this->__load();
        return parent::getValidTimeStart();
    }

    public function setValidTimeEnd($validTimeEnd)
    {
        $this->__load();
        return parent::setValidTimeEnd($validTimeEnd);
    }

    public function getValidTimeEnd()
    {
        $this->__load();
        return parent::getValidTimeEnd();
    }

    public function setHouse($house)
    {
        $this->__load();
        return parent::setHouse($house);
    }

    public function getHouse()
    {
        $this->__load();
        return parent::getHouse();
    }

    public function setStreet($street)
    {
        $this->__load();
        return parent::setStreet($street);
    }

    public function getStreet()
    {
        $this->__load();
        return parent::getStreet();
    }

    public function setVilege($vilege)
    {
        $this->__load();
        return parent::setVilege($vilege);
    }

    public function getVilege()
    {
        $this->__load();
        return parent::getVilege();
    }

    public function setDistrict($district)
    {
        $this->__load();
        return parent::setDistrict($district);
    }

    public function getDistrict()
    {
        $this->__load();
        return parent::getDistrict();
    }

    public function setQuarter($quarter)
    {
        $this->__load();
        return parent::setQuarter($quarter);
    }

    public function getQuarter()
    {
        $this->__load();
        return parent::getQuarter();
    }

    public function setCity($city)
    {
        $this->__load();
        return parent::setCity($city);
    }

    public function getCity()
    {
        $this->__load();
        return parent::getCity();
    }

    public function setLongitude($longitude)
    {
        $this->__load();
        return parent::setLongitude($longitude);
    }

    public function getLongitude()
    {
        $this->__load();
        return parent::getLongitude();
    }

    public function setLatitude($latitude)
    {
        $this->__load();
        return parent::setLatitude($latitude);
    }

    public function getLatitude()
    {
        $this->__load();
        return parent::getLatitude();
    }

    public function setCreatedUser(\RealEstate\Entity\User $createdUser = NULL)
    {
        $this->__load();
        return parent::setCreatedUser($createdUser);
    }

    public function getCreatedUser()
    {
        $this->__load();
        return parent::getCreatedUser();
    }

    public function setLastModifiedUser(\RealEstate\Entity\User $lastModifiedUser = NULL)
    {
        $this->__load();
        return parent::setLastModifiedUser($lastModifiedUser);
    }

    public function getLastModifiedUser()
    {
        $this->__load();
        return parent::getLastModifiedUser();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'pid', 'hidden', 'disabled', 'deleted', 'createdTime', 'lastModifiedTime', 'validTimeStart', 'validTimeEnd', 'house', 'street', 'vilege', 'district', 'quarter', 'city', 'longitude', 'latitude', 'createdUser', 'lastModifiedUser');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}