<?php

namespace DoctrineORMModule\Proxy\__CG__\RealEstate\Entity;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class PersonalDetail extends \RealEstate\Entity\PersonalDetail implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["id"];
        }
        $this->__load();
        return parent::getId();
    }

    public function setPid($pid)
    {
        $this->__load();
        return parent::setPid($pid);
    }

    public function getPid()
    {
        $this->__load();
        return parent::getPid();
    }

    public function setHidden($hidden)
    {
        $this->__load();
        return parent::setHidden($hidden);
    }

    public function getHidden()
    {
        $this->__load();
        return parent::getHidden();
    }

    public function setDisabled($disabled)
    {
        $this->__load();
        return parent::setDisabled($disabled);
    }

    public function getDisabled()
    {
        $this->__load();
        return parent::getDisabled();
    }

    public function setDeleted($deleted)
    {
        $this->__load();
        return parent::setDeleted($deleted);
    }

    public function getDeleted()
    {
        $this->__load();
        return parent::getDeleted();
    }

    public function setCreatedTime($createdTime)
    {
        $this->__load();
        return parent::setCreatedTime($createdTime);
    }

    public function getCreatedTime()
    {
        $this->__load();
        return parent::getCreatedTime();
    }

    public function setLastModifiedTime($lastModifiedTime)
    {
        $this->__load();
        return parent::setLastModifiedTime($lastModifiedTime);
    }

    public function getLastModifiedTime()
    {
        $this->__load();
        return parent::getLastModifiedTime();
    }

    public function setValidTimeStart($validTimeStart)
    {
        $this->__load();
        return parent::setValidTimeStart($validTimeStart);
    }

    public function getValidTimeStart()
    {
        $this->__load();
        return parent::getValidTimeStart();
    }

    public function setValidTimeEnd($validTimeEnd)
    {
        $this->__load();
        return parent::setValidTimeEnd($validTimeEnd);
    }

    public function getValidTimeEnd()
    {
        $this->__load();
        return parent::getValidTimeEnd();
    }

    public function setFirstname($firstname)
    {
        $this->__load();
        return parent::setFirstname($firstname);
    }

    public function getFirstname()
    {
        $this->__load();
        return parent::getFirstname();
    }

    public function setLastname($lastname)
    {
        $this->__load();
        return parent::setLastname($lastname);
    }

    public function getLastname()
    {
        $this->__load();
        return parent::getLastname();
    }

    public function setGender($gender)
    {
        $this->__load();
        return parent::setGender($gender);
    }

    public function getGender()
    {
        $this->__load();
        return parent::getGender();
    }

    public function setJob($job)
    {
        $this->__load();
        return parent::setJob($job);
    }

    public function getJob()
    {
        $this->__load();
        return parent::getJob();
    }

    public function setAge($age)
    {
        $this->__load();
        return parent::setAge($age);
    }

    public function getAge()
    {
        $this->__load();
        return parent::getAge();
    }

    public function setEmail($email)
    {
        $this->__load();
        return parent::setEmail($email);
    }

    public function getEmail()
    {
        $this->__load();
        return parent::getEmail();
    }

    public function setPhoneNumber1($phoneNumber1)
    {
        $this->__load();
        return parent::setPhoneNumber1($phoneNumber1);
    }

    public function getPhoneNumber1()
    {
        $this->__load();
        return parent::getPhoneNumber1();
    }

    public function setPhoneNumber2($phoneNumber2)
    {
        $this->__load();
        return parent::setPhoneNumber2($phoneNumber2);
    }

    public function getPhoneNumber2()
    {
        $this->__load();
        return parent::getPhoneNumber2();
    }

    public function setOthers($others)
    {
        $this->__load();
        return parent::setOthers($others);
    }

    public function getOthers()
    {
        $this->__load();
        return parent::getOthers();
    }

    public function setCreatedUser(\RealEstate\Entity\User $createdUser = NULL)
    {
        $this->__load();
        return parent::setCreatedUser($createdUser);
    }

    public function getCreatedUser()
    {
        $this->__load();
        return parent::getCreatedUser();
    }

    public function setLastModifiedUser(\RealEstate\Entity\User $lastModifiedUser = NULL)
    {
        $this->__load();
        return parent::setLastModifiedUser($lastModifiedUser);
    }

    public function getLastModifiedUser()
    {
        $this->__load();
        return parent::getLastModifiedUser();
    }

    public function setUser(\RealEstate\Entity\User $user = NULL)
    {
        $this->__load();
        return parent::setUser($user);
    }

    public function getUser()
    {
        $this->__load();
        return parent::getUser();
    }

    public function setType(\RealEstate\Entity\PersonalType $type = NULL)
    {
        $this->__load();
        return parent::setType($type);
    }

    public function getType()
    {
        $this->__load();
        return parent::getType();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'pid', 'hidden', 'disabled', 'deleted', 'createdTime', 'lastModifiedTime', 'validTimeStart', 'validTimeEnd', 'firstname', 'lastname', 'gender', 'job', 'age', 'email', 'phoneNumber1', 'phoneNumber2', 'others', 'createdUser', 'lastModifiedUser', 'user', 'type');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}