<?php

namespace DoctrineORMModule\Proxy\__CG__\RealEstate\Entity;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class UserRole extends \RealEstate\Entity\UserRole implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function getRoleId()
    {
        if ($this->__isInitialized__ === false) {
            return $this->_identifier["roleId"];
        }
        $this->__load();
        return parent::getRoleId();
    }

    public function setDefault($default)
    {
        $this->__load();
        return parent::setDefault($default);
    }

    public function getDefault()
    {
        $this->__load();
        return parent::getDefault();
    }

    public function setParent($parent)
    {
        $this->__load();
        return parent::setParent($parent);
    }

    public function getParent()
    {
        $this->__load();
        return parent::getParent();
    }

    public function addPermission(\RealEstate\Entity\Permission $permission)
    {
        $this->__load();
        return parent::addPermission($permission);
    }

    public function removePermission(\RealEstate\Entity\Permission $permission)
    {
        $this->__load();
        return parent::removePermission($permission);
    }

    public function getPermission()
    {
        $this->__load();
        return parent::getPermission();
    }

    public function addUser(\RealEstate\Entity\User $user)
    {
        $this->__load();
        return parent::addUser($user);
    }

    public function removeUser(\RealEstate\Entity\User $user)
    {
        $this->__load();
        return parent::removeUser($user);
    }

    public function getUser()
    {
        $this->__load();
        return parent::getUser();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'roleId', 'default', 'parent', 'permission', 'user');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}