<?php echo $this->doctype(); ?>
<html lang="en">
    <head>
        <meta charset="utf-8">
		<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" /> 
        <meta name="description" content="Company description here" /> 
        <meta name="keywords" content="Company keywords here" />
		<?php echo $this->headTitle('ZF2 ' . $this->translate('Skeleton Application'))->setSeparator(' - ')->setAutoEscape(false) ?>

		<?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0') ?>

        <!-- Le styles -->
		<?php
		echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/images/favicon.ico'))
				->prependStylesheet($this->basePath() . '/css/bootstrap-responsive.min.css')
				->prependStylesheet($this->basePath() . '/css/style.css')
				->prependStylesheet($this->basePath() . '/css/bootstrap.min.css')
		?>

        <!-- Scripts -->
		<?php
		echo $this->headScript()->prependFile($this->basePath() . '/js/html5.js', 'text/javascript', array('conditional' => 'lt IE 9',))
				->prependFile($this->basePath() . '/js/bootstrap.min.js')
				->prependFile($this->basePath() . '/js/jquery.min.js')
		?>

    </head>
    <body>
        <link rel="stylesheet" type="text/css" media="all" href="css/reset.css" /> 
		<link rel="stylesheet" type="text/css" media="all" href="../css/text.css" /> 
		<link rel="stylesheet" type="text/css" media="all" href="../css/layout.css" />
		<link rel="stylesheet" type="text/css" media="print" href="../css/print.css" />

		<link href='http://fonts.googleapis.com/css?family=Arimo' rel='stylesheet' type='text/css' />
		<script type="text/javascript" src="../js/script.js"></script>

		<div id="head">
			<div id="logo">
				<img src="../picture/logo.png" alt=""/>
			</div>
			<div id="Hnav">
				<ul>
					<li class="active"><a class="active" href="#home">Home</a></li>
					<li><a href="#news">News</a></li>
					<li><a href="#contact">Contact</a></li>
					<li><a href="#about">About</a></li>
					<li><a href="#news">News</a></li>
					<li><a href="#contact">Contact</a></li>
					<li><a href="#about">About</a></li>
				</ul>

			</div>
		</div>

		<div id="main-content">
			<div id="colum-left">
				<div class="category">
					<h2>Category</h2>
					<ul>
						<li><a href="#">Lorem ipsum dolor sit amet</a></li>
						<li><a href="#">Lorem ipsum dolor sit amet</a></li>
						<li><a href="#">Lorem ipsum dolor sit amet</a></li>
						<li><a href="#">Lorem ipsum dolor sit amet</a></li>
						<li><a href="#">Lorem ipsum dolor sit amet</a></li>
						<li><a href="#">Lorem ipsum dolor sit amet</a></li>

					</ul>
				</div>
				<div class="category">
					<h2>Category</h2>
					<ul>
						<li><a href="#">Lorem ipsum dolor sit amet</a></li>
						<li><a href="#">Lorem ipsum dolor sit amet</a></li>
						<li><a href="#">Lorem ipsum dolor sit amet</a></li>
						<li><a href="#">Lorem ipsum dolor sit amet</a></li>
						<li><a href="#">Lorem ipsum dolor sit amet</a></li>
						<li><a href="#">Lorem ipsum dolor sit amet</a></li>

					</ul>
				</div>

				<div class="info-img">
					<img src="../picture/info-img.png" alt=""/>
				</div>
				<div class="info-img">
					<img src="../picture/info-img.png" alt=""/>
				</div>

			</div>

			<div class="container">
				<?php echo $this->content; ?>
			</div> <!-- /container -->
			<div id="footer">
				<div id="footer-nav">
					<ul>
						<li class="active"><a  class="active" href="#home">Home &nbsp; |</a></li>
						<li><a href="#news">News &nbsp; |</a></li>
						<li><a href="#contact">Contact &nbsp; |</a></li>
						<li><a href="#about">About &nbsp; |</a></li>
						<li><a href="#news">News &nbsp; |</a></li>
						<li><a href="#contact">Contact &nbsp; |</a></li>
						<li><a href="#about">About</a></li>
					</ul>

				</div>
				<p> Copyright<sup>&copy;</sup> by BST Web best solution team.</p>
			</div>
			<?php echo $this->inlineScript() ?>
    </body>
</html>
