<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="utf-8">
		<?php echo $this->headTitle($this->translate('Realestate'))->setSeparator(' - ')->setAutoEscape(false) ?>
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<meta name="description" content="">
		<meta name="author" content="">

		<!-- Le styles -->
		<?php echo $this->headLink()->prependStylesheet('/assets/css/bootstrap.min.css') ?>
		<?php echo $this->headLink()->prependStylesheet('/assets/css/bootstrap-responsive.min.css') ?>

		<!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
		<!--[if lt IE 9]>
		  <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
		<![endif]-->

		<!-- Fav and touch icons -->
		<link rel="apple-touch-icon-precomposed" sizes="144x144" href="/assets/ico/apple-touch-icon-144-precomposed.png">
		<link rel="apple-touch-icon-precomposed" sizes="114x114" href="/assets/ico/apple-touch-icon-114-precomposed.png">
		<link rel="apple-touch-icon-precomposed" sizes="72x72" href="/assets/ico/apple-touch-icon-72-precomposed.png">
		<link rel="apple-touch-icon-precomposed" href="/assets/ico/apple-touch-icon-57-precomposed.png">
		<link rel="shortcut icon" href="../assets/ico/favicon.png">

		<script src="/assets/js/jquery-1.9.0.min.js"></script>

		<?php echo $this->headLink()->prependStylesheet('/assets/css/main-style.css') ?>
	</head>

	<body>

		<div class="container-narrow">

			<div class="masthead">
				<ul class="nav nav-tabs nav-pills pull-right">
					<li><a href="<?php echo $this->url('home') ?>">Home</a></li>
					<li class="dropdown">
						<a class="dropdown-toggle" data-toggle="dropdown" href="#">House<b class="caret"></b></a>
						<ul class="dropdown-menu">
							<li><a href="<?php echo $this->url('create/action', array('action' => 'house')) ?>">Create</a></li>
						</ul>
					</li>
					<li class="dropdown">
						<a class="dropdown-toggle" data-toggle="dropdown" href="#">User<b class="caret"></b></a>
						<ul class="dropdown-menu">
							<li><a href="<?php echo $this->url('zfcuser/login') ?>">Login</a></li>
						</ul>
					</li>
					<li class="dropdown">
						<a class="dropdown-toggle" data-toggle="dropdown" href="#">Admin<b class="caret"></b></a>
						<ul class="dropdown-menu">
							<li><a href="<?php echo $this->url('zfcadmin/zfcuseradmin/list') ?>">List users</a></li>
						</ul>
					</li>
				</ul>
				<h3 class="muted">Realestate</h3>
			</div>

			<?php echo $this->content; ?>

			<div class="footer">
				<p>&copy; Company 2012</p>
			</div>

		</div> <!-- /container -->

		<!-- Le javascript
		================================================== -->
		<!-- Placed at the end of the document so the pages load faster -->
		<script src="/assets/js/bootstrap-transition.js"></script>
		<script src="/assets/js/bootstrap-alert.js"></script>
		<script src="/assets/js/bootstrap-modal.js"></script>
		<script src="/assets/js/bootstrap-dropdown.js"></script>
		<script src="/assets/js/bootstrap-scrollspy.js"></script>
		<script src="/assets/js/bootstrap-tab.js"></script>
		<script src="/assets/js/bootstrap-tooltip.js"></script>
		<script src="/assets/js/bootstrap-popover.js"></script>
		<script src="/assets/js/bootstrap-button.js"></script>
		<script src="/assets/js/bootstrap-collapse.js"></script>
		<script src="/assets/js/bootstrap-carousel.js"></script>
		<script src="/assets/js/bootstrap-typeahead.js"></script>

	</body>
</html>
