<?php echo $this->doctype(); ?>
<html lang="en">
	<head>
		<meta charset="utf-8">
		<?php echo $this->headTitle('RealEstate Management System')->setSeparator(' - ')->setAutoEscape(false) ?>

		<?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0') ?>

		<!-- Le styles -->
		<?php echo $this->headLink()->prependStylesheet('/css/bootstrap.min.css') ?>
		<?php echo $this->headLink()->prependStylesheet('/css/bootstrap-responsive.min.css') ?>
		<?php echo $this->headLink()->prependStylesheet('/css/main-style.css') ?>

		<!-- Scripts -->
		<?php
//		echo $this->headScript()->prependFile('/js/html5.js', 'text/javascript', array('conditional' => 'lt IE 9',))
//				->prependFile('/js/jquery.min.js')
//				->prependFile('/js/bootstrap.min.js')
		?>

	</head>

	<body>

		<div class="navbar navbar-fixed-top">
			<div class="navbar-inner">
				<div class="container">
					<a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">

						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
					</a>
					<a class="brand" href="<?php echo $this->url('home') ?>">Home</a>
					<div class="nav-collapse">
						<?php
						echo $this->navigation('admin_navigation')
								->menu()
								->setUlClass('nav')
								->setMaxDepth(0)
								->setRenderInvisible(false)
						?>
					</div><!--/.nav-collapse -->
				</div>
			</div>
		</div>

		<div id="content" class="container">
			<?php echo $this->content; ?>
			<hr>
		</div> <!-- /container -->
		<footer class="container">
			<p>&copy; 2013</p>
		</footer>
		<?php echo $this->inlineScript() ?>
	</body>
</html>
