<div style="padding: 10px;border: solid #5bc0de 2px;border-radius: 15px;">
	<div class="navbar-form" style="padding: 10px;height:400px;overflow: scroll;">
		<small>Result for : <?php echo $term ?></small>
		<table class="table table-bordered">
			<tbody>
				<?php
//				echo count($houses);
//				for ($i = 0; $i < count($houses); $i++) {
//					echo $houses;
					foreach ($houses as $house) {
//						show houses which search
						echo '<tr>';
						echo '<td>';
						echo '<a href="' . $this->url('details', array('username' => $house->getCreatedUser()->getUsername(), 'propertyType' => 'house', 'propertyId' => $house->getId())) . '">';
						echo preg_replace('/'.$term.'/','<b>'.$term.'</b>', $house->getAddress()->getHouse()). ', ' . preg_replace('/'.$term.'/', '<b>'.$term.'</b>', $house->getAddress()->getStreet()) . '<br />';
						echo '</a>';
						echo preg_replace('/'.$term.'/i', '<b>'.$term.'</b>', $house->getAddress()->getAddress()). '<br />';
						echo preg_replace('/'.$term.'/', '<b>'.$term.'</b>', $house->getCost()) . ' ៛/month';
						echo '</td>';
						echo '</tr>';
					}
//				}
				?>
			</tbody>
		</table>
	</div>
</div>