<?php

foreach ($houses as $house) {
	echo '<pre>';
	echo '<a href="' . $this->url('details', array('username' => $house->getCreatedUser()->getUsername(), 'propertyType' => 'house', 'propertyId' => $house->getId())) . '">';
	echo $house->getAddress()->getHouse() . ' ' . $house->getAddress()->getVillage() . '<br />';
	echo '</a>';
	echo $house->getCost() . '<br />';
	echo $house->getType()->getTitle() . '<br />';
	echo '<a class="addRoom" href="' . $this->url('room/action', array('action' => 'new')) . '">Add room</a>';

	echo '</pre>';
}
?>

<?php echo $this->paginationControl($houses, 'Sliding', 'real-estate/houses-list/pagination-house-list.phtml'); ?>

<link rel="stylesheet" href="/assets/css/colorbox.css" />
<script src="/assets/js/jquery.colorbox.js"></script>
<script type="text/javascript">
	jQuery(".addRoom").colorbox();
</script>