<?php
foreach ($houses as $house) {
	echo '<pre>';
	echo '<a href="' . $this->url('details', array('username' => $house->getCreatedUser()->getUsername(), 'propertyType' => 'house', 'propertyId' => $house->getId())) . '">';
	echo $house->getAddress()->getHouse() . ' ' . $house->getAddress()->getVillage() . '<br />';
	echo '</a>';
	echo $house->getCost() . '<br />';
	echo $house->getType()->getTitle() . '<br />';

	if (0 < count($rooms[$house->getId()])) {
		echo count($rooms[$house->getId()]) . ' rooms available';
		foreach ($rooms[$house->getId()] as $room) {
			echo '<br />' . $room->getCost() . ' (' . $room->getSize()->getWidth() . 'x' . $room->getSize()->getHeight() . 'x' . $room->getSize()->getLength() . ') ';
		}
	}
	echo '<br /><a class="addRoom" href="' . $this->url('room/action', array('action' => 'new', 'houseId' => $house->getId())) . '">Add room</a>';

	echo '</pre>';
}
?>

<?php echo $this->paginationControl($houses, 'Sliding', 'real-estate/houses-list/pagination-house-list.phtml'); ?>

<link rel="stylesheet" href="/assets/css/colorbox.css" />
<script src="/assets/js/jquery.colorbox.js"></script>
<script type="text/javascript">
	//	jQuery(".addRoom").colorbox();
</script>