<a href="<?php echo $this->url('message') ?>" class="btn">Back to message</a>

<hr />

<?php
$form->prepare();
$form->setAttribute('action', $this->url('message/action', array('action' => 'new')));
$form->setAttribute('method', 'post');
?>
<?php echo $this->form()->openTag($form) ?>
<dl>
	<?php foreach ($form as $element): ?>
		<dd><?php echo $this->formRow($element) ?></dd>
	<?php endforeach ?>
</dl>
<?php echo $this->form()->closeTag() ?>