<div id="thumbnail">
    
    <div class="thumImgSmall">
        <img/>
        <img/>
        <img/>
        <img/>
        
    </div>
</div>

<?php
if (NULL === $oneHouse && NULL !== $houses && NULL !== $user) {
    foreach ($houses as $house) {
        echo '<pre>';
//		echo '<a href="' . $this->url('details', array('username' => $house->getCreatedUser()->getUsername(), 'propertyType' => 'house', 'propertyId' => $house->getId())) . '">';
        echo $house->getAddress()->getHouse() . ' ' . $house->getAddress()->getStreet() . '<br />';
        echo '</a>';
		echo $house->getAddress()->getAddress() . '<br />';
        echo $house->getCost() . '<br />';
        echo $house->getType()->getTitle() . '<br />';
        echo '</pre>';
    }
} else if (NULL !== $oneHouse) {
    echo '<pre>';
    echo 'Address : ' . $oneHouse->getAddress()->getHouse() . ' ' . $oneHouse->getAddress()->getStreet() . '<br />';
	echo $oneHouse->getAddress()->getAddress() . '<br />';
    echo 'Price : ' . $oneHouse->getCost() . '<br />';
    echo 'Type : ' . $oneHouse->getType()->getTitle() . '<br />';
    echo '</pre>';
    ?>
<div id="comments">
    <?php
    if (NULL !== $comments) {
        if (is_array($comments)) {
            foreach ($comments as $comment) {
                echo '<div class="commentContent">';
                echo '<img class="profileImg" src"" alt />';
                echo '<div class="acticale"><label class="UserName">' . $comment->getUser()->getUsername() . '</label>  ' . '<div class="commentText">' . $comment->getContent() . '</div></div>';

                echo'</div>';
            }
        }
    }
    ?>
</div>
    <input type="hidden" id="mostRecentCommentTime" value="<?php echo $mostRecentCommentTime ?>"/>
    <input type="hidden" id="isSendToServer" value="1" />
    <?php
    if (NULL !== $form) {
        echo '<div class= "commentContent">';
        echo '<img class="profileImg" src"" alt />';
//        echo '<label class"userName">'.$currentUser->getUsername() . ' </label>';
        echo '<div id="searchBox">'.$this->formRow($form->get('content')).'</div>';
        echo $this->formRow($form->get('submit'));
        echo '</div>';
        ?>

        <script type="text/javascript">
            jQuery(document).ready(function(){
                jQuery('#commentButton').click(function(){
                    var commentContent = jQuery('#commentTextarea').val();
                    if('' !== commentContent && null !== commentContent){
                        jQuery.ajax({
                            'url' : "<?php echo $this->url('comment'); ?>",
                            'type' : "post",
                            'data' : {'houseId':"<?php echo $oneHouse->getId() ?>",'comment':commentContent},
                            'success' : function(data){
                                console.log(data);
                                if(1 == parseInt(data)){
                                    jQuery('#commentTextarea').val('');
                                    jQuery('#commentButton').val('Comment');
                                }else{
                                    jQuery('#commentButton').val('CAN\'T ADD YOUR COMMENT');
                                }
                            }
                        });	
                    }
                });
            });
        </script>
        <?php
    }
}
?>
<script type="text/javascript">
    setInterval(function() {
        if(1 == jQuery("#isSendToServer").val()){
            jQuery.ajax({
                'url' : "<?php echo $this->url('get-comments') ?>",
                'type' : 'post',
                'data' : {'mostRecentCommentTime':jQuery('#mostRecentCommentTime').val(), 'houseId':"<?php echo $oneHouse->getId() ?>"},
                'beforeSend' : function(){
                    jQuery("#isSendToServer").val(0);
                },
                'complete': function(){
                    jQuery("#isSendToServer").val(1);
                },
                'success' : function(data){
                    var result = jQuery.parseJSON(data);
                    jQuery('#mostRecentCommentTime').val(result.newTime);
                    var comments = result.comments;
                    console.log(data);				
                    if(comments.length > 0){
                        jQuery.each(comments, function(index, comment) {
                            var string = '<div class="commentContent">'
                    +'<img class="profileImg" src"" alt />';
                            string += '<label class="UserName">'+comment.username + '</label>  ' ;
                            string += '<div class="comment">'+comment.content + '</div>' ;
                            jQuery('#comments').append(string+'</div>');
                        });
                    }
                }
            });
        }
    }, 2500);
</script>