<?php
if (NULL === $oneHouse && NULL !== $houses && NULL !== $user) {
	foreach ($houses as $house) {
		echo '<pre>';
//		echo '<a href="' . $this->url('details', array('username' => $house->getCreatedUser()->getUsername(), 'propertyType' => 'house', 'propertyId' => $house->getId())) . '">';
		echo $house->getAddress()->getHouse() . ' ' . $house->getAddress()->getVillage() . '<br />';
		echo '</a>';
		echo $house->getCost() . '<br />';
		echo $house->getType()->getTitle() . '<br />';
		echo '</pre>';
	}
} else if (NULL !== $oneHouse) {
	echo '<pre>';
	echo $oneHouse->getAddress()->getHouse() . ' ' . $oneHouse->getAddress()->getVillage() . '<br />';
	echo $oneHouse->getCost() . '<br />';
	echo $oneHouse->getType()->getTitle() . '<br />';
	echo '</pre>';
	?>
	<div id="comments">
		<?php
		if (NULL !== $comments) {
			if (is_array($comments)) {
				foreach ($comments as $comment) {
					echo $comment->getUser()->getUsername() . ' : ' . $comment->getContent() . '<br /><br />';
				}
			}
		}
		?>
		<input type="hidden" id="mostRecentCommentTime" value="<?php echo $mostRecentCommentTime ?>"/>
	</div>
	<?php
	if (NULL !== $form) {
		echo $user->getUsername() . ' ';
		echo $this->formRow($form->get('content'));
		echo $this->formRow($form->get('submit'));
		?>

		<script type="text/javascript">
			jQuery(document).ready(function(){
				jQuery('#commentButton').click(function(){
					var commentContent = jQuery('#commentTextarea').val();
					if('' !== commentContent && null !== commentContent){
						jQuery.ajax({
							url : "<?php echo $this->url('comment'); ?>",
							type : "post",
							data : {'houseId':"<?php echo $oneHouse->getId() ?>",'comment':commentContent},
							success : function(data){
								console.log(data);
								if(1 == parseInt(data)){
									jQuery('#commentTextarea').val('');
									jQuery('#commentButton').val('Comment');
								}else{
									jQuery('#commentButton').val('CAN\'T ADD YOUR COMMENT');
								}
							}
						});	
					}
				});
			});
		</script>
		<?php
	}
}
?>
<script type="text/javascript">
	setInterval(function() {
		jQuery.ajax({
			url : "<?php echo $this->url('get-comments') ?>",
			type : 'post',
			data : {'mostRecentCommentTime':jQuery('#mostRecentCommentTime').val(), 'houseId':"<?php echo $oneHouse->getId() ?>"},
			success : function(data){

				var result = jQuery.parseJSON(data);
				jQuery('#mostRecentCommentTime').val(result.newTime);
				var comments = result.comments;
				console.log(data);				
				if(comments.length > 0){
					jQuery.each(comments, function(index, comment) {
						var string = '';
						string += comment.username + ' : ' ;
						string += comment.content + '<br /><br />' ;
						jQuery('#comments').append(string);
					});
				}
			}
		});
	}, 2500);
</script>