<script src="http://maps.google.com/maps/api/js?key=AIzaSyAkB1TsoIYZew4q0Cfb1X0RkI-iTbDzWsg&sensor=true" type="text/javascript"></script>
<script type="text/javascript" src="/assets/js/map.info.box.js"></script>

<script type="text/javascript">
	//<![CDATA[

	var customIcons = {
		speeder: {
			icon: 'http://labs.google.com/ridefinder/images/mm_20_blue.png',
			shadow: 'http://labs.google.com/ridefinder/images/mm_20_shadow.png'
		}
	};
	var infoWindow = new google.maps.InfoWindow();
	var infoBoxArray = [];
	function loadMap() {
		var lat = null;
		var lng = null;
		
		navigator.geolocation.getCurrentPosition(function(position){
			lat = position.coords.latitude;
			lng = position.coords.longitude;
			console.log(lat);
			console.log(lng);
		});
		
		if(null == lat){
			lat = 11.570696416360889;
		}
		
		if(null == lng){
			lng = 104.89734779752325;
		}
		
		var map = new google.maps.Map(document.getElementById("map"), {
			center: new google.maps.LatLng(lat, lng),
			zoom: 12,
			mapTypeId: google.maps.MapTypeId.ROADMAP
		});
		
		// Change this depending on the name of your PHP file
		downloadUrl("<?php echo $this->url('map/action', array('action' => 'show')) ?>", function(data) {
			var xml = data.responseXML;
			var markers = xml.documentElement.getElementsByTagName("marker");
			for (var i = 0; i < markers.length; i++) {
				var name = markers[i].getAttribute("name");
				var address = markers[i].getAttribute("address");
				var type = markers[i].getAttribute("type");
				var point = new google.maps.LatLng(
				parseFloat(markers[i].getAttribute("lat")),
				parseFloat(markers[i].getAttribute("lng")));
				var html = "<b>" + name + "</b> <br/>" + address;
				var icon = customIcons[type] || {};
				var marker = new google.maps.Marker({
					map: map,
					position: point,
					icon: icon.icon,
					shadow: icon.shadow
				});
				bindInfoWindow(marker, map, infoWindow, html);
			}
		});
	}

	function bindInfoWindow(marker, map, infoWindow, html) {
		google.maps.event.addListener(marker, 'click', function() {
			if (infoBoxArray) {
				for (i in infoBoxArray) {
					infoBoxArray[i].setMap(null);
				}
			}
			
			infoBoxArray = new Array();
			
			infoBoxArray.push(new InfoBox({
				latlng: marker.getPosition(), 
				map: map,
				content: html
			}));
			
			//			infoWindow.setContent(html);
			//			infoWindow.open(map, marker);
		});
	}

	function downloadUrl(url, callback) {
		var request = window.ActiveXObject ?
			new ActiveXObject('Microsoft.XMLHTTP') :
			new XMLHttpRequest;

		request.onreadystatechange = function() {
			if (request.readyState == 4) {
				request.onreadystatechange = function(){};
				callback(request, request.status);
			}
		};

		request.open('GET', url, true);
		request.send(null);
	}
	
	jQuery(document).ready(function(){
		loadMap();
	});
	
	//]]>
</script>

<div id="map" style="width: 100%; height: 400px"></div>