<div id="ceateHousePage">
	<h1>Create house</h1>

	<?php
	$form->prepare();
	$form->setAttribute('action', $this->url('create/action', array('action' => 'house')));
	$form->setAttribute('method', 'post');
	?>
	<?php echo $this->form()->openTag($form) ?>

	<dl>
		<?php foreach ($form as $element): ?>
			<dd><?php echo $this->formRow($element) ?></dd>
		<?php endforeach ?>
	</dl>
	<div id="map" style="width:100%; height:300px"></div>
	<br /><br />
	<input class="btn btn-large btn-success" type="submit" value="Add" />
	<?php echo $this->form()->closeTag() ?>

	<script type="text/javascript">
		jQuery(".select").chosen();
	</script>
</script>

<script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=AIzaSyAkB1TsoIYZew4q0Cfb1X0RkI-iTbDzWsg&sensor=false"></script>
<script type="text/javascript" src="/assets/js/map.info.box.js"></script>

<script type="text/javascript">
	var map;
	var housePosition;
	var markersArray = [];
	var infoBoxArray = new Array();
	
	var geocoder;
	var infowindow = new google.maps.InfoWindow();
	var marker;
	
	
	jQuery(document).ready(function(){
		initialize();
	});
	
	jQuery('#address').dblclick(function(){
		jQuery(this).removeAttr("readonly");
	});
	
	jQuery('#address').blur(function(){
		jQuery(this).attr("readonly", true);
	});
	
	function initialize() {
		geocoder = new google.maps.Geocoder();
	
		var lat = null;
		var lng = null;
		
		navigator.geolocation.getCurrentPosition(function(position){
			lat = position.coords.latitude;
			lng = position.coords.longitude;
			console.log(lat);
			console.log(lng);
		});
		
		if(null == lat){
			lat = 11.570696416360889;
		}
		
		if(null == lng){
			lng = 104.89734779752325;
		}
		
		var myLatlng = new google.maps.LatLng(lat,lng);
		var mapOptions = {
			zoom: 14,
			center: myLatlng,
			mapTypeId: google.maps.MapTypeId.ROADMAP
		}
		map = new google.maps.Map(document.getElementById("map"), mapOptions);

		google.maps.event.addListener(map, 'click', function(event) {
			var lat = event.latLng.lat();
			var lng = event.latLng.lng();
			var latlng = new google.maps.LatLng(lat, lng);
			geocoder.geocode({'latLng': latlng}, function(results, status) {
				if (status == google.maps.GeocoderStatus.OK) {
					if (results[1]) {
						marker = new google.maps.Marker({
							position: latlng,
							map: map,
							icon: '/glyphicons/glyphicons_020_home.png'
						});
						
						markersArray.push(marker);
						if (infoBoxArray) {
							for (i in infoBoxArray) {
								infoBoxArray[i].setMap(null);
							}
						}
						
						infoBoxArray = new Array();
						
						infoBoxArray.push(new InfoBox({
							latlng: marker.getPosition(), 
							map: map,
							content: results[1].formatted_address
						}));
						
						jQuery('#address').val(results[1].formatted_address);
					}
				} else {
					// TODO ERROR HANDLING
					alert("Geocoder failed due to: " + status);
				}
			});
		});

		google.maps.event.addListener(map, 'click', function(event) {
			housePosition = new google.maps.Marker({
				position: event.latLng,
				title:"Your house",
				icon: '/glyphicons/glyphicons_020_home.png'
			});
			markersArray.push(housePosition);
				
			if (markersArray) {
				for (i in markersArray) {
					markersArray[i].setMap(null);
				}
			}
				
			housePosition.setMap(map);

			jQuery('#latitude').val(event.latLng.lat());
			jQuery('#longitude').val(event.latLng.lng());
		});
			
		var image = '/glyphicons/glyphicons_003_user.png'
		var userPosition = new google.maps.Marker({
			position: myLatlng,
			map: map,
			title:"Your current location",
			icon: 'http://maps.google.com/mapfiles/arrow.png'
		});
			
	}

</script>

<!-- TinyMCE -->
<script type="text/javascript" src="/tinymce/tiny_mce.js"></script>
<script type="text/javascript">
	tinyMCE.init({
		// General options
		mode : "textareas",
		theme : "advanced",
		plugins : "pagebreak,style,layer,table,advlink,emotions,iespell,insertdatetime,preview,searchreplace,print,paste,directionality,noneditable,visualchars,xhtmlxtras,template,wordcount,advlist"
	});
</script>
<style>
	.defaultSkin table
	/*.defualtSkin tbody, */
	/*.defaultSkin a, */
	/*.defaultSkin img, */
	/*.defaultSkin tr, */
	/*.defaultSkin div*/
	/*.defaultSkin td*/
	/*.defaulfSkin span*/
	/*.defaultSkin *,*/
	/*.defaltSkin .mceText*/
	{
		background: none repeat scroll 0 0 #ffffff;
	}

</style>
<!-- /TinyMCE -->

</div>